language: cpp

######################
# Operating systems
######################
os:
  - linux
  - osx


######################
# Compilers
######################
compiler:
  - gcc
  - clang


######################
# Install dependencies
######################
install:
  - sudo apt-get install autoconf automake libtool curl make g++ unzip
  - git clone https://github.com/protocolbuffers/protobuf.git
  - cd protobuf && mkdir build && cd build && cmake ../cmake && make && make install


######################
# Create build directory
######################
before_script:
  - mkdir build
  - cd build


######################
# cmake and build
######################
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DDUMMY_BUILD_TESTS=ON ..
  - make
  - make test
