language: cpp

######################
# Operating systems
######################
os:
  - linux
  - osx


######################
# Compilers
######################
compiler:
  - gcc
  - clang


######################
# Install dependencies
######################
install:
  - wget https://github.com/protocolbuffers/protobuf/archive/v3.12.3.tar.gz
  - tar -xzvf v3.12.3.tar.gz
  - pushd protobuf-3.12.3 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd


######################
# Create build directory
######################
before_script:
  - mkdir build
  - cd build


######################
# cmake and build
######################
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DDUMMY_BUILD_TESTS=ON ..
  - make
  - make test
