language: cpp

######################
# Operating systems
######################
os:
  - linux
  - osx


######################
# Compilers
######################
compiler:
  - gcc
  - clang


######################
# Install dependencies
######################
install:
  - ./ci/install-protobuf.sh


######################
# Create build directory
######################
before_script:
  - mkdir build
  - cd build


######################
# cmake and build
######################
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DDUMMY_BUILD_TESTS=ON ..
  - make
  - make test
